### ISSUE TITLE
Running on real robot

### ISSUE THREAD

**Issue by agdt008** [cshizhe/onav_rim#5]
Thank you for amazing work!. I downloaded trained model from the link given. Would you like to provide guidance on using trained model on real robot? Thank you for help.

**Comment by cshizhe** [comment]
Hi, thanks for your interest in our work. To run the model on real robot, it is better to modify the camera configuration to train the model as shown in the Table VI in our paper. What other information do you want to know?

**Comment by agdt008** [comment]
Hi, thank you for reply. Currently I have only Jetson orin to run model. I have robot with ROS environment. I can get RGBD images and robot current pose data. Now when I see the trained model folder from dropbox link. It has "gibson-2plus-resnet50.pth" and also "rednet_semmap_mp3d_tuned.pth" and there is also ckpt "model_step_54426.pt". Which one to use for experiement and what are the inputs and outputs of these models? Thank you for guidance and help!

**Comment by cshizhe** [comment]
This released model is just for evaluation in the simulator for fair comparison with prior work. For the real world application, we train another navigation model with modified camera configurations as explained in the paper and we remove the agent pose from the input. Please check the paper for more details.
