### ISSUE TITLE
Directories depth, rgb, seg and top_down_map are empty after evaluation script finished.

### ISSUE THREAD

**Issue by NakashimaTakeshi** [cshizhe/onav_rim#8]
Thank you for the excellent research.

Following the [README.md](https://github.com/cshizhe/onav_rim/blob/main/README.md), I executed the steps of Evaluate the model.
In this part, directories depth, rgb, seg, top_down_map  are created [here](https://github.com/cshizhe/onav_rim/blob/1849a57561ac26ccd1a662d24b00aeafce2b529e/habitat_baselines/il/env_based/il_trainer.py#L163), but after it finishes, these directories remain empty.
Is there an option to display these results also during validation episodes?
I am particularly interested in explicit map reconstruction.

![image](https://github.com/cshizhe/onav_rim/assets/83634813/cfb0973c-6836-4f06-8495-13113399a609)

**Comment by cshizhe** [comment]
Hi, if you set VIDEO_OPTION in config file, you could generate video visualizations as shown [here](https://github.com/cshizhe/onav_rim/blob/main/habitat_baselines/il/env_based/il_trainer.py#L814).

**Comment by NakashimaTakeshi** [comment]
Thank you for your reply.
Is the VIDEO_OPTION you mentioned the one described [here](https://github.com/cshizhe/onav_rim/blob/1849a57561ac26ccd1a662d24b00aeafce2b529e/habitat_baselines/README.md#additional-utilities)?

When I specify VIDEO_OPTION as "disk", the exploring movie are saved in the VIDEO_DIR directory specified by the [script](https://github.com/cshizhe/onav_rim/blob/main/job_scripts/onav_eval_transformer.sh#L45) provided in the README instructions. However, the depth, rgb, seg, top_down_map directories i mentioned above is still empty.

**Comment by cshizhe** [comment]
You could save the depth etc. following the same manner.
